name: deploy to production
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/nixlabs-dev/website:${{github.sha}}
  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://74.113.97.40:6443
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            .kube/deployment.yaml
            .kube/ingress.yaml
            .kube/service.yaml
          images: |
            ghcr.io/nixlabs-dev/website:${{github.sha}}